apiVersion: v2
name: pearl
description: A Helm chart for Pearl API, UI and DB

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.1.2
appVersion: "1.16.0"
